### ISSUE TITLE
[BUG] - Inconsistent rewards across explorers and query results

### ISSUE THREAD

**Issue by jiagengliu** [IntersectMBO/cardano-node#4072] opened 2022-06-21 18:38 UTC
**Internal/External**
*External*

**Area**
*Other* 
Query - Reward calculation 

**Summary**
Each explorer produces a different result for the same reward balance, and all are different from the result of `cardano-cli query`. I'm not sure who's responsible for the problem but it's weird how this is the case. 

**Steps to reproduce**
1. Find the current pool operator of HEART pool across explorers (just an example; I'm *not* associated with HEART pool): [Cardanoscan](https://cardanoscan.io/stakekey/295500b9ab745777a56f2d86b3f968cebad11f13d6e2b9d5c2954d97), [Adapools](https://adapools.org/stake/e1295500b9ab745777a56f2d86b3f968cebad11f13d6e2b9d5c2954d97), [Adastat](https://adastat.net/accounts/295500b9ab745777a56f2d86b3f968cebad11f13d6e2b9d5c2954d97)
2. Get the reward balance of the same account with `cardano-cli query ledger-state --mainnet > ledger-state.json`. The JSON path is ``stateBefore - esLState - delegationState - dstate - rewards``. 
3. Note the difference across the four results. Right now Cardanoscan says 5429 ADA; AdaPools says 5141 ADA; AdaStat says 5431 ADA; CLI query says 5042 ADA. Which one is the "true" value? 

**Expected behavior**
Explorers and Cardano CLI query should produce the same reward balance. 

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04
- Node version: cardano-node 1.32.1 - linux-x86_64 - ghc-8.10 git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648
- CLI version: cardano-cli 1.32.1 - linux-x86_64 - ghc-8.10 git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648

**Additional context**
The explorers report different rewards of the HEART pool for Epoch 322. Cardanoscan and PoolTool report 644 ADA. Adapools and AdaStat report 257 ADA. Cardano CLI doesn't seem to provide the data.

**Comment by rdlrt** [comment] 2022-06-22 00:21
I am not sure if it's correct to have the issue on node repository. The problem is alignment between explorers (as they may use different backends, and/or similar queries).

It is one of the precise goals why [Koios](https://api.koios.rest) got created - to open source the queries used for a given backend and try to align, atleast between folks who would like to participate on an open-source backend.

To compare your query result:
1. CLI:
``` bash
cardano-cli query stake-address-info --address stake1uy542q9e4d69waa9dukcdvledr8t45glz0tw9ww4c225m9cm836js --mainnet
[
    {
        "delegation": "pool1lzupr43772kfux007sdt02vlx7uzmfcplrwmxntdztxmwv9myrj",
        "address": "stake1uy542q9e4d69waa9dukcdvledr8t45glz0tw9ww4c225m9cm836js",
        "rewardAccountBalance": 5042067918
    }
]
```
2. DBSync queried using Koios (query [here](https://github.com/cardano-community/guild-operators/blob/alpha/files/grest/rpc/account/account_info.sql) ):
``` bash
curl -X GET "https://api.koios.rest/api/v0/account_info?_address=stake1uy542q9e4d69waa9dukcdvledr8t45glz0tw9ww4c225m9cm836js"
[
  {
    "status": "registered",
    "delegated_pool": "pool1lzupr43772kfux007sdt02vlx7uzmfcplrwmxntdztxmwv9myrj",
    "total_balance": "5140883928",
    "utxo": "98816010",
    "rewards": "5042067918",
    "withdrawals": "0",
    "rewards_available": "5042067918",
    "reserves": "0",
    "treasury": "0"
  }
]
```

As you'd see:
1. CLI and Koios show exact amounts
2. ADAPools shows `total_balance` (not just rewards part), which is exactly same again.

I assume CardanoScan and Pooltool currently add reward from next epoch , which is not yet available from Node - to be checked.

> The explorers report different rewards of the HEART pool for Epoch 322. Cardanoscan and PoolTool report 644 ADA. Adapools and AdaStat report 257 ADA. Cardano CLI doesn't seem to provide the data.

From what I see, ADApools, ADAStat, Koios all [report 257 ADA](https://api.koios.rest/#get-/pool_history) as delegator rewards for mentioned pool at epoch 322. We'd predominantly have to check with the respective explorers to see how they extract[ed] the reward information to look at the anomaly.

**Comment by CarlosLopezDeLara** [comment] 2022-06-22 01:32
@jiagengliu 

What @rdlrt just said is exactly right. So this is not a bug for this repository.  I'm closing it. 
I guess explorers could make more explicit what is exactly what they are showing and the method they use to calculate it, so that it is clear for the users.

**Closed as completed by CarlosLopezDeLara** 2022-06-22 01:32 UTC
Labels: type: not a bug, user type: external
